version: '3'
services:
  web:
    build: .
    container_name: "shop_python"
#    restart: always
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    ports:
        - "8000:8000"
    volumes:
        - .:/shop
    links:
        - db
    depends_on:
        - db
        - redis
    command: >
      sh -c "
             python3 manage.py makemigrations &&
             python3 manage.py migrate &&
             python3 manage.py wait_for_db &&
             python3 manage.py runserver 0.0.0.0:8000"

  db:
    container_name: "shop_db"
    image: "postgres:14-alpine"
    ports:
        - "54321:5432"
    env_file:
      - .env
    volumes:
#      - pgdata:/var/lib/postgresql/data
      - /shop/:/var/lib/postgresql/data

  redis:
    container_name: 'shop_redis'
    hostname: redis
    image: "redis:5.0-alpine"
    ports:
      - "63791:6379"
    expose:
      - "6379"
    volumes:
      - redis_data:/data

#  redis:
#    container_name: "custom_redis"
#    image: "redis:5.0-alpine"
#    ports:
#      - '0.0.0.0:6380:6379'
#    volumes:
#      - redis_data:/data
#  redis:
#    container_name: "custom_redis"
#    image: "redis:5.0-alpine"
#    command: --port 6379
#    ports:
#      - '6379:6379'
#    volumes:
#      - redis_data:/data

volumes:
  pgdata:
  redis_data:
