# Generated by Django 4.1.2 on 2022-10-12 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knox', '0008_remove_authtoken_salt'),
        ('core', '0006_alter_token_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('authtoken_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='knox.authtoken')),
                ('user_agent', models.CharField(max_length=255, null=True)),
            ],
            bases=('knox.authtoken',),
        ),
        migrations.DeleteModel(
            name='Token',
        ),
    ]
