# Generated by Django 4.1.2 on 2022-10-17 22:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinion',
            name='status_show',
            field=models.CharField(default='H', max_length=1),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
