# Generated by Django 4.1.2 on 2022-10-17 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_opinion_status_show_alter_productitem_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='status_show',
            field=models.CharField(choices=[('S', 'SHOW'), ('H', 'HIDDEN'), ('U', 'UNDER REVIEW')], default='H', max_length=1),
        ),
    ]
