# Generated by Django 4.1.2 on 2022-10-18 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_shop_cart'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='opinion',
            unique_together=set(),
        ),
    ]
