# Generated by Django 4.1.2 on 2022-10-25 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_cartitem_product_alter_shop_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='opinion',
            name='product',
        ),
        migrations.RemoveField(
            model_name='opinion',
            name='user',
        ),
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='product',
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='score',
            name='product',
        ),
        migrations.RemoveField(
            model_name='score',
            name='user',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='user',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.DeleteModel(
            name='Opinion',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductItem',
        ),
        migrations.DeleteModel(
            name='Score',
        ),
        migrations.DeleteModel(
            name='Shop',
        ),
    ]
